# Copyright The Linux Foundation and each contributor to CommunityBridge.
# SPDX-License-Identifier: MIT
swagger: '2.0'
info:
  title: EasyCLA API
  version: '1.0.0'
basePath: /v4
schemes:
  - http

consumes:
  - application/json
produces:
  - application/json

#securityDefinitions:
#  OauthSecurity:
#    type: oauth2
#    flow: accessCode
#    authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth'
#    tokenUrl: 'https://www.googleapis.com/oauth2/v4/token'
#    scopes:
#      admin: LF Admin scope
#      project: Project Manager scope
#      company: CLA Manager scope
#      contrib: Contributor scope

#security:
#  - OauthSecurity: []

tags:
  - name: service
  - name: easycla

paths:
  /ops/health:
    get:
      summary: API Health Check
      security: []
      description: The health and status of the EasyCLA API service
      operationId: getHealth
      produces:
        - application/json
      responses:
        '200':
          description: 'Success'
          headers:
            X-REQUEST-ID:
              type: string
              description: Request ID
          schema:
            $ref: '#/definitions/health'
        '400':
          $ref: '#/responses/invalid-request'
        '401':
          $ref: '#/responses/unauthorized'
        '403':
          $ref: '#/responses/forbidden'
        '404':
          $ref: '#/responses/not-found'
        '503':
          description: ''
          schema:
            $ref: '#/definitions/health'
      tags:
        - health

  /api-docs:
    get:
      security: []
      summary: Get swagger documentation
      description: Renders the API Documentation has an interactive HTML page.
      operationId: getDoc
      produces:
        - text/html
      responses:
        200:
          description: Success
      tags:
        - docs

  /swagger.json:
    get:
      security: []
      summary: Get swagger JSON
      description: Returns the swagger specification as a JSON document.
      operationId: getSwagger
      produces:
        - application/json
      responses:
        200:
          description: Success
      tags:
        - docs

  /orgs/{salesForceOrganizationId}:
    get:
      security: []
      summary: list foundations affiliated with the organization
      description: Returns list of foundations affiliated with the organization of organization manager
      operationId: getOrgFoundations
      parameters:
        - name: salesForceOrganizationId
          description: SalesForce ID of organization
          in: path
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/organization'
        '400':
          $ref: '#/responses/invalid-request'
        '401':
          $ref: '#/responses/unauthorized'
        '403':
          $ref: '#/responses/forbidden'
        '404':
          $ref: '#/responses/not-found'
      tags:
        - organization

  /project/{projectID}:
    get:
      security: []
      summary: Get project
      description: Returns details of the project
      operationId: getProject
      parameters:
        - name: projectID
          description: ID of the project
          in: path
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/project'
        '400':
          $ref: '#/responses/invalid-request'
        '401':
          $ref: '#/responses/unauthorized'
        '403':
          $ref: '#/responses/forbidden'
        '404':
          $ref: '#/responses/not-found'
      tags:
        - project


definitions:
  health:
    type: object
    title: Health
    properties:
      TimeStamp:
        description: The overall timestamp of the health check
        example: "2019-10-15T16:06:15Z"
        type: string
        x-omitempty: false
      Status:
        description: The overall status of the health check
        example: "healthy"
        type: string
        x-omitempty: false
      Version:
        description: The version tag of the service related to this health check
        example: "v0.1.35"
        type: string
        x-omitempty: false
      Githash:
        description: The git hash of the service related to this health check
        example: "e96f055"
        type: string
        x-omitempty: false
      Branch:
        description: The git branch of the service related to this health check
        example: "master"
        type: string
        x-omitempty: false
      BuildTimeStamp:
        description: The build timestamp of the service related to this health check
        example: "2019-10-15T09:05:34-0700"
        type: string
        x-omitempty: false
      Healths:
        description: An array of components or sub-components for this health check
        type: array
        items:
          $ref: '#/definitions/health-status'

  health-status:
    type: object
    title: Health Status
    properties:
      Name:
        description: The name of the component or sub-component related to this health check.
        example: "CLA - DynamoDB"
        type: string
        x-omitempty: false
      Duration:
        description: The time it took to gather the health status
        example: "8.481802ms"
        type: string
        x-omitempty: false
      Healthy:
        description: A flag indicating if this health status is health or not
        example: true
        type: boolean
        x-omitempty: false
      Error:
        description: An optional error message indicating the reason for the failed health check.
        example: "unable to connect to database - permission denied"
        type: string
      TimeStamp:
        example: "2019-10-15T16:07:43Z"
        description: The timestamp of the health check
        type: string
        x-omitempty: false

  error-response:
    type: object
    title: Error Response
    description: Standard error format
    properties:
      Code:
        type: string
        description: The code for the error response
        example: "403"
        pattern: '^([1-9][\d]+){1,}$'
      Message:
        type: string
        description: The message for the error response
        example: "Not authorized"
        pattern: '^([\w\d\s\-\,\./]+){2,}$'

  organization:
    type: object
    additionalProperties:
      type: array
      items:
        $ref: '#/definitions/foundation'

  foundation:
    type: object
    properties:
      foundationId:
        type: string
      claGroups:
        type: array
        items:
          type: object
          additionalProperties:
            type: object
            $ref: '#/definitions/clagroup'

  clagroup:
    type: object
    title: cla group
    description: cla group details
    properties:
      claGroupId:
        type: string
      organizationSigned:
        type: boolean
      waitingForSignature:
        type: boolean
      employeesSigned:
        type: integer
      employeesPending:
        type: integer
      projectsCovered:
        type: array
        items:
          type: string

  project:
    type: object
    properties:
      projectID:
        type: string
      projectName:
        type: string
      templates:
        type: array
        items:
          $ref: '#/definitions/claTemplate'
      cclaEnabled:
        type: boolean
      iclaEnabled:
        type: boolean
      iclaSignatureRequired:
        type: boolean
      cclaCompaniesSigned:
        type: array
        items:
          type: string
      whitelist:
        $ref: '#/definitions/whitelist'

  claTemplate:
    type: object
    properties:
      type:
        type: string
      legalEntityName:
        type: string
      author:
        type: string
      url:
        type: string
      version:
        type: string
      created:
        type: string
      updated:
        type: string

  whitelist:
    type: object
    properties:
      users:
        type: array
        items:
          type: object
          $ref: '#/definitions/whitelistedUser'
      domains:
        type: array
        items:
          type: object
          $ref: '#/definitions/whitelistedDomain'
      emails:
        type: array
        items:
          type: object
          $ref: '#/definitions/whitelistedEmail'
      githubUsers:
        type: array
        items:
          type: object
          $ref: '#/definitions/whitelistedGithubUser'
      githubOrgs:
        type: array
        items:
          type: object
          $ref: '#/definitions/whitelistedGithubOrgs'

  whitelistedUser:
    type: object
    properties:
      userID:
        type: string
      signed:
        type: boolean
      signed_on:
        type: string
      last_activity:
        type: string

  whitelistedDomain:
    type: object
    properties:
      domain:
        type: string

  whitelistedEmail:
    type: object
    properties:
      email:
        type: string

  whitelistedGithubUser:
    type: object
    properties:
      githubUser:
        type: string

  whitelistedGithubOrgs:
    type: object
    properties:
      githubOrg:
        type: string

responses:
  unauthorized:
    description: Unauthorized
    schema:
      $ref: '#/definitions/error-response'
  invalid-request:
    description: Invalid request
    schema:
      $ref: '#/definitions/error-response'
  forbidden:
    description: Insufficient privilege to execute action.
    schema:
      $ref: '#/definitions/error-response'
  not-found:
    description: Not found
    schema:
      $ref: '#/definitions/error-response'
  #conflict:
  #  description: The request could not be completed due to a conflict with the current state of the target resource.
  #  schema:
  #    $ref: '#/definitions/error-response'

