version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.13-node
    working_directory: /go/src/github.com/communitybridge/easycla-api
    steps:
      - checkout
      - restore_cache:
          name: Restore Cache
          keys:
            - dep-packages-{{ checksum "Gopkg.lock" }}
      - run:
          name: Install and setup
          command: make setup
      - run:
          name: Install cover
          command: go get golang.org/x/tools/cmd/cover
      - add_ssh_keys:
          fingerprints:
            - "aa:a4:6b:7e:51:9c:31:a3:10:5a:43:e2:e4:87:b7:c0"
      - run:
          name: Swagger Code Generation
          command: make swagger
      - run:
          name: Swagger Code Spec Validation
          command: make swagger-valiate
      - run:
          name: Download dependencies
          command: make deps
      - run:
          name: Lint
          command: make lint
      - run:
          name: Test
          command: make test
      - save_cache:
          name: Save Dep Cache
          key: dep-packages-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
            - node_modules
      - persist_to_workspace:
          root: ./
          paths:
            - vendor
            - node_modules

workflows:
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
