version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.13-node
        environment:
          DATABASE_URL: postgres://test:test@127.0.0.1:5432/cla-test?sslmode=disable
          TEST_DATABASE_DSN: dbname=cla-test password=test user=test port=5432 sslmode=disable
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: test
          POSTGRES_DB: cla-test
          POSTGRES_PASSWORD: test

    working_directory: /go/src/github.com/communitybridge/easycla-api
    steps:
      - checkout
      - restore_cache:
          name: Restore Cache
          keys:
            - dep-packages-{{ checksum "Gopkg.lock" }}
      - run:
          name: Install and setup
          command: make setup
      - run:
          name: Install cover
          command: go get golang.org/x/tools/cmd/cover
      - add_ssh_keys:
          fingerprints:
            - "b2:f9:8f:56:21:28:e1:de:70:ad:60:b1:21:c9:bd:5d"
      - run:
          name: Swagger Code Generation
          command: make swagger
      - run:
          name: Swagger Code Spec Validation
          command: make swagger-validate
      - run:
          name: Download dependencies
          command: make deps
      - run:
          name: Lint
          command: make lint
      - run:
          name: Prepare test database
          command: dbmate -d ".build/db/migrations" -s ".build/db/schema.sql" up
      - run:
          name: Test
          command: make test
      - save_cache:
          name: Save Dep Cache
          key: dep-packages-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
            - node_modules
      - persist_to_workspace:
          root: ./
          paths:
            - vendor
            - node_modules

workflows:
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
